name: Build

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - 'release-*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      # build only source bundle because this is more faster !
      - name: Build 2D
        run: npm run build:2d:src

      - name: Build 3D
        run: npm run build:3d:src
